[package]
name = "ame_bus_macros"
version = "0.1.0"
edition = "2021"
[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
proc-macro2 = "1.0"
convert_case = "0.7.1"
quote = "1"